site_name: TODO
site_description: TODO
site_author: Cédric Belin - cedric@belin.io
site_url: https://cedx.github.io/yii2-free-mobile

docs_dir: doc
site_dir: web

repo_name: GitHub
repo_url: https://github.com/cedx/yii2-free-mobile
edit_uri: ''

copyright: Copyright &copy; TODO Cédric Belin
google_analytics:
- !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
- auto

extra:
  social:
  - {type: globe, link: 'https://belin.io'}
  - {type: github, link: 'https://github.com/cedx'}
  - {type: twitter, link: 'https://twitter.com/cedxbelin'}
  - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
- admonition
- codehilite

pages:
- Overview: index.md
- Installation: installation.md
- Usage: TODO.md
- About:
  - Changelog: about/changelog.md
  - License: about/license.md
  - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: blue grey, accent: light blue}
